//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQWELogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQWELogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ApplicationLogo {
            get {
                object obj = ResourceManager.GetObject("ApplicationLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- CQ-WE Contest Settings file for 2011 --&gt;
        ///&lt;!-- Modified by N4HAI on 09/09/2011 --&gt;
        ///
        ///&lt;Settings date=&quot;09/09/2011&quot;&gt;
        ///  &lt;Instructions&gt;
        ///    &lt;LogSubmission instructions =&quot;To submit the CQ-WE log, locate the log file and email it to your coordinator.  Normally, the log file resides in &amp;quot;My Documents&amp;quot; and is named &amp;quot;CQWELog_&amp;lt;year&amp;gt;_&amp;lt;your callsign&amp;gt;.xml&amp;quot;.  To see the full path to your log file, double click on the log file name shown at the bottom of the main program screen.&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CQWEContestSettings {
            get {
                return ResourceManager.GetString("CQWEContestSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WELogo32x32 {
            get {
                object obj = ResourceManager.GetObject("WELogo32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
